steps:
  # 1. Build the APP Image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'VITE_APP_MODE=APP',
      '--build-arg', 'VITE_FIREBASE_API_KEY=$_FIREBASE_API_KEY',
      '--build-arg', 'VITE_FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN',
      '--build-arg', 'VITE_FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/onlineeverywhere-repo/app-suite:$COMMIT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/onlineeverywhere-repo/app-suite:latest',
      '.'
    ]
    id: 'Build App Image'

  # 2. Build the MARKETING SITE
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd marketing-site && \
        npm install && \
        npm run build
    id: 'Build Marketing Site'

  # 3. Push Images (App only)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/onlineeverywhere-repo/app-suite:$COMMIT_SHA']
    id: 'Push App Image'

  # 4. Deploy APP to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'app-suite',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/onlineeverywhere-repo/app-suite:$COMMIT_SHA',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]
    id: 'Deploy App'

  # 5. Deploy MARKETING SITE to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-d', 'marketing-site/dist', 'gs://$_MARKETING_BUCKET']
    id: 'Deploy Marketing Site'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FIREBASE_API_KEY: "CHANGE_ME"
  _FIREBASE_AUTH_DOMAIN: "ole-f8b3b.firebaseapp.com"
  _FIREBASE_PROJECT_ID: "ole-f8b3b"
  _MARKETING_BUCKET: "www.onlineverywhere.com"
